// Code generated by goyacc -o filter_grammar.go -p scimFilter filter_grammar.y. DO NOT EDIT.

// This file is the source grammar for filter_grammar.go, generated via:
//
//	go tool goyacc -o filter_grammar.go -p scimFilter filter_grammar.y
//
// Each rule below implements exactly one production of the SCIM filter
// ABNF grammar, per RFC 7644, Section 3.4.2.2:
//
//	FILTER    = attrExp / logExp / valuePath / *1"not" "(" FILTER ")"
//	valuePath = attrPath "[" valFilter "]"
//	valFilter = attrExp / logExp / *1"not" "(" valFilter ")"
//	attrExp   = (attrPath SP "pr") / (attrPath SP compareOp SP compValue)
//	compValue = false / null / true / number / string
//	compareOp = "eq" / "ne" / "co" / "sw" / "ew" / "gt" / "lt" / "ge" / "le"
//	logExp    = FILTER SP ("and" / "or") SP FILTER
//	attrPath  = [URI ":"] ATTRNAME *1subAttr
//
//line filter_grammar.y:2
package protocol

import __yyfmt__ "fmt"

//line filter_grammar.y:17

//line filter_grammar.y:20
type scimFilterSymType struct {
	yys    int
	str    string
	filter Filter
	path   AttrPath
	value  any
}

const tATTRPATH = 57346
const tAND = 57347
const tOR = 57348
const tNOT = 57349
const tPR = 57350
const tEQ = 57351
const tNE = 57352
const tCO = 57353
const tSW = 57354
const tEW = 57355
const tGT = 57356
const tGE = 57357
const tLT = 57358
const tLE = 57359
const tTRUE = 57360
const tFALSE = 57361
const tNULL = 57362
const tSTRING = 57363
const tNUMBER = 57364
const tLPAREN = 57365
const tRPAREN = 57366
const tLBRACKET = 57367
const tRBRACKET = 57368

var scimFilterToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tATTRPATH",
	"tAND",
	"tOR",
	"tNOT",
	"tPR",
	"tEQ",
	"tNE",
	"tCO",
	"tSW",
	"tEW",
	"tGT",
	"tGE",
	"tLT",
	"tLE",
	"tTRUE",
	"tFALSE",
	"tNULL",
	"tSTRING",
	"tNUMBER",
	"tLPAREN",
	"tRPAREN",
	"tLBRACKET",
	"tRBRACKET",
}

var scimFilterStatenames = [...]string{}

const scimFilterEofCode = 1
const scimFilterErrCode = 2
const scimFilterInitialStackSize = 16

//line filter_grammar.y:229

//line yacctab:1
var scimFilterExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const scimFilterPrivate = 57344

const scimFilterLast = 94

var scimFilterAct = [...]int8{
	8, 46, 12, 3, 10, 11, 30, 44, 44, 45,
	10, 44, 45, 44, 45, 35, 1, 16, 31, 15,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 43,
	52, 2, 51, 36, 5, 35, 14, 32, 31, 13,
	4, 47, 26, 27, 28, 35, 35, 35, 31, 31,
	31, 48, 49, 50, 15, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 10, 11, 38, 37, 39, 41,
	40, 10, 11, 9, 9, 0, 33, 6, 0, 0,
	0, 0, 0, 42, 0, 0, 0, 0, 0, 0,
	29, 0, 34, 7,
}

var scimFilterPact = [...]int16{
	70, -32768, -1, -32768, -32768, -32768, -21, 70, 11, -32768,
	70, 70, 70, 66, 69, -32768, 48, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, 5, 59, -32768,
	3, -32768, -32768, -22, 69, 46, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, 69, 69, 69, 8, -32768, 2,
	6, -32768, -32768,
}

var scimFilterPgo = [...]int8{
	0, 31, 6, 40, 37, 3, 34, 0, 33, 17,
	16,
}

var scimFilterR1 = [...]int8{
	0, 10, 1, 1, 1, 1, 1, 3, 3, 6,
	2, 2, 2, 2, 4, 4, 5, 5, 9, 9,
	9, 9, 9, 9, 9, 9, 9, 8, 8, 8,
	8, 8, 7,
}

var scimFilterR2 = [...]int8{
	0, 1, 1, 1, 1, 4, 3, 3, 3, 4,
	1, 1, 4, 3, 3, 3, 2, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1,
}

var scimFilterChk = [...]int16{
	-32768, -10, -1, -5, -3, -6, 7, 23, -7, 4,
	5, 6, 23, -1, 25, 8, -9, 9, 10, 11,
	12, 13, 14, 15, 16, 17, -1, -1, -1, 24,
	-2, -5, -4, 7, 23, -7, -8, 19, 18, 20,
	22, 21, 24, 26, 5, 6, 23, -2, -2, -2,
	-2, 24, 24,
}

var scimFilterDef = [...]int8{
	0, -2, 1, 2, 3, 4, 0, 0, 0, 32,
	0, 0, 0, 0, 0, 16, 0, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 7, 8, 0, 6,
	0, 10, 11, 0, 0, 0, 17, 27, 28, 29,
	30, 31, 5, 9, 0, 0, 0, 0, 14, 15,
	0, 13, 12,
}

var scimFilterTok1 = [...]int8{
	1,
}

var scimFilterTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var scimFilterTok3 = [...]int8{
	0,
}

var scimFilterErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	scimFilterDebug        = 0
	scimFilterErrorVerbose = false
)

type scimFilterLexer interface {
	Lex(lval *scimFilterSymType) int
	Error(s string)
}

type scimFilterParser interface {
	Parse(scimFilterLexer) int
	Lookahead() int
}

type scimFilterParserImpl struct {
	lval  scimFilterSymType
	stack [scimFilterInitialStackSize]scimFilterSymType
	char  int
}

func (p *scimFilterParserImpl) Lookahead() int {
	return p.char
}

func scimFilterNewParser() scimFilterParser {
	return &scimFilterParserImpl{}
}

const scimFilterFlag = -32768

func scimFilterTokname(c int) string {
	if c >= 1 && c-1 < len(scimFilterToknames) {
		if scimFilterToknames[c-1] != "" {
			return scimFilterToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func scimFilterStatname(s int) string {
	if s >= 0 && s < len(scimFilterStatenames) {
		if scimFilterStatenames[s] != "" {
			return scimFilterStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func scimFilterErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !scimFilterErrorVerbose {
		return "syntax error"
	}

	for _, e := range scimFilterErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + scimFilterTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(scimFilterPact[state])
	for tok := TOKSTART; tok-1 < len(scimFilterToknames); tok++ {
		if n := base + tok; n >= 0 && n < scimFilterLast && int(scimFilterChk[int(scimFilterAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if scimFilterDef[state] == -2 {
		i := 0
		for scimFilterExca[i] != -1 || int(scimFilterExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; scimFilterExca[i] >= 0; i += 2 {
			tok := int(scimFilterExca[i])
			if tok < TOKSTART || scimFilterExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if scimFilterExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += scimFilterTokname(tok)
	}
	return res
}

func scimFilterlex1(lex scimFilterLexer, lval *scimFilterSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(scimFilterTok1[0])
		goto out
	}
	if char < len(scimFilterTok1) {
		token = int(scimFilterTok1[char])
		goto out
	}
	if char >= scimFilterPrivate {
		if char < scimFilterPrivate+len(scimFilterTok2) {
			token = int(scimFilterTok2[char-scimFilterPrivate])
			goto out
		}
	}
	for i := 0; i < len(scimFilterTok3); i += 2 {
		token = int(scimFilterTok3[i+0])
		if token == char {
			token = int(scimFilterTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(scimFilterTok2[1]) /* unknown char */
	}
	if scimFilterDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", scimFilterTokname(token), uint(char))
	}
	return char, token
}

func scimFilterParse(scimFilterlex scimFilterLexer) int {
	return scimFilterNewParser().Parse(scimFilterlex)
}

func (scimFilterrcvr *scimFilterParserImpl) Parse(scimFilterlex scimFilterLexer) int {
	var scimFiltern int
	var scimFilterVAL scimFilterSymType
	var scimFilterDollar []scimFilterSymType
	_ = scimFilterDollar // silence set and not used
	scimFilterS := scimFilterrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	scimFilterstate := 0
	scimFilterrcvr.char = -1
	scimFiltertoken := -1 // scimFilterrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		scimFilterstate = -1
		scimFilterrcvr.char = -1
		scimFiltertoken = -1
	}()
	scimFilterp := -1
	goto scimFilterstack

ret0:
	return 0

ret1:
	return 1

scimFilterstack:
	/* put a state and value onto the stack */
	if scimFilterDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", scimFilterTokname(scimFiltertoken), scimFilterStatname(scimFilterstate))
	}

	scimFilterp++
	if scimFilterp >= len(scimFilterS) {
		nyys := make([]scimFilterSymType, len(scimFilterS)*2)
		copy(nyys, scimFilterS)
		scimFilterS = nyys
	}
	scimFilterS[scimFilterp] = scimFilterVAL
	scimFilterS[scimFilterp].yys = scimFilterstate

scimFilternewstate:
	scimFiltern = int(scimFilterPact[scimFilterstate])
	if scimFiltern <= scimFilterFlag {
		goto scimFilterdefault /* simple state */
	}
	if scimFilterrcvr.char < 0 {
		scimFilterrcvr.char, scimFiltertoken = scimFilterlex1(scimFilterlex, &scimFilterrcvr.lval)
	}
	scimFiltern += scimFiltertoken
	if scimFiltern < 0 || scimFiltern >= scimFilterLast {
		goto scimFilterdefault
	}
	scimFiltern = int(scimFilterAct[scimFiltern])
	if int(scimFilterChk[scimFiltern]) == scimFiltertoken { /* valid shift */
		scimFilterrcvr.char = -1
		scimFiltertoken = -1
		scimFilterVAL = scimFilterrcvr.lval
		scimFilterstate = scimFiltern
		if Errflag > 0 {
			Errflag--
		}
		goto scimFilterstack
	}

scimFilterdefault:
	/* default state action */
	scimFiltern = int(scimFilterDef[scimFilterstate])
	if scimFiltern == -2 {
		if scimFilterrcvr.char < 0 {
			scimFilterrcvr.char, scimFiltertoken = scimFilterlex1(scimFilterlex, &scimFilterrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if scimFilterExca[xi+0] == -1 && int(scimFilterExca[xi+1]) == scimFilterstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			scimFiltern = int(scimFilterExca[xi+0])
			if scimFiltern < 0 || scimFiltern == scimFiltertoken {
				break
			}
		}
		scimFiltern = int(scimFilterExca[xi+1])
		if scimFiltern < 0 {
			goto ret0
		}
	}
	if scimFiltern == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			scimFilterlex.Error(scimFilterErrorMessage(scimFilterstate, scimFiltertoken))
			Nerrs++
			if scimFilterDebug >= 1 {
				__yyfmt__.Printf("%s", scimFilterStatname(scimFilterstate))
				__yyfmt__.Printf(" saw %s\n", scimFilterTokname(scimFiltertoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for scimFilterp >= 0 {
				scimFiltern = int(scimFilterPact[scimFilterS[scimFilterp].yys]) + scimFilterErrCode
				if scimFiltern >= 0 && scimFiltern < scimFilterLast {
					scimFilterstate = int(scimFilterAct[scimFiltern]) /* simulate a shift of "error" */
					if int(scimFilterChk[scimFilterstate]) == scimFilterErrCode {
						goto scimFilterstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if scimFilterDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", scimFilterS[scimFilterp].yys)
				}
				scimFilterp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if scimFilterDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", scimFilterTokname(scimFiltertoken))
			}
			if scimFiltertoken == scimFilterEofCode {
				goto ret1
			}
			scimFilterrcvr.char = -1
			scimFiltertoken = -1
			goto scimFilternewstate /* try again in the same state */
		}
	}

	/* reduction by production scimFiltern */
	if scimFilterDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", scimFiltern, scimFilterStatname(scimFilterstate))
	}

	scimFilternt := scimFiltern
	scimFilterpt := scimFilterp
	_ = scimFilterpt // guard against "declared and not used"

	scimFilterp -= int(scimFilterR2[scimFiltern])
	// scimFilterp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if scimFilterp+1 >= len(scimFilterS) {
		nyys := make([]scimFilterSymType, len(scimFilterS)*2)
		copy(nyys, scimFilterS)
		scimFilterS = nyys
	}
	scimFilterVAL = scimFilterS[scimFilterp+1]

	/* consult goto table to find next state */
	scimFiltern = int(scimFilterR1[scimFiltern])
	scimFilterg := int(scimFilterPgo[scimFiltern])
	scimFilterj := scimFilterg + scimFilterS[scimFilterp].yys + 1

	if scimFilterj >= scimFilterLast {
		scimFilterstate = int(scimFilterAct[scimFilterg])
	} else {
		scimFilterstate = int(scimFilterAct[scimFilterj])
		if int(scimFilterChk[scimFilterstate]) != -scimFiltern {
			scimFilterstate = int(scimFilterAct[scimFilterg])
		}
	}
	// dummy call; replaced with literal code
	switch scimFilternt {

	case 1:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:48
		{
			scimFilterlex.(*filterLex).setResult(scimFilterDollar[1].filter)
		}
	case 2:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:62
		{
			scimFilterVAL.filter = scimFilterDollar[1].filter
		}
	case 3:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:66
		{
			scimFilterVAL.filter = scimFilterDollar[1].filter
		}
	case 4:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:70
		{
			scimFilterVAL.filter = scimFilterDollar[1].filter
		}
	case 5:
		scimFilterDollar = scimFilterS[scimFilterpt-4 : scimFilterpt+1]
//line filter_grammar.y:74
		{
			scimFilterVAL.filter = &NotExpr{Expr: scimFilterDollar[3].filter}
		}
	case 6:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:78
		{
			scimFilterVAL.filter = scimFilterDollar[2].filter
		}
	case 7:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:86
		{
			scimFilterVAL.filter = &LogicalExpr{Op: "and", Left: scimFilterDollar[1].filter, Right: scimFilterDollar[3].filter}
		}
	case 8:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:90
		{
			scimFilterVAL.filter = &LogicalExpr{Op: "or", Left: scimFilterDollar[1].filter, Right: scimFilterDollar[3].filter}
		}
	case 9:
		scimFilterDollar = scimFilterS[scimFilterpt-4 : scimFilterpt+1]
//line filter_grammar.y:98
		{
			scimFilterVAL.filter = &ValuePathExpr{Attribute: scimFilterDollar[1].path.Attribute, Sub: scimFilterDollar[3].filter}
		}
	case 10:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:109
		{
			scimFilterVAL.filter = scimFilterDollar[1].filter
		}
	case 11:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:113
		{
			scimFilterVAL.filter = scimFilterDollar[1].filter
		}
	case 12:
		scimFilterDollar = scimFilterS[scimFilterpt-4 : scimFilterpt+1]
//line filter_grammar.y:117
		{
			scimFilterVAL.filter = &NotExpr{Expr: scimFilterDollar[3].filter}
		}
	case 13:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:121
		{
			scimFilterVAL.filter = scimFilterDollar[2].filter
		}
	case 14:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:128
		{
			scimFilterVAL.filter = &LogicalExpr{Op: "and", Left: scimFilterDollar[1].filter, Right: scimFilterDollar[3].filter}
		}
	case 15:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:132
		{
			scimFilterVAL.filter = &LogicalExpr{Op: "or", Left: scimFilterDollar[1].filter, Right: scimFilterDollar[3].filter}
		}
	case 16:
		scimFilterDollar = scimFilterS[scimFilterpt-2 : scimFilterpt+1]
//line filter_grammar.y:140
		{
			scimFilterVAL.filter = &AttrExpr{Path: scimFilterDollar[1].path, Op: OpPresent}
		}
	case 17:
		scimFilterDollar = scimFilterS[scimFilterpt-3 : scimFilterpt+1]
//line filter_grammar.y:144
		{
			scimFilterVAL.filter = &AttrExpr{Path: scimFilterDollar[1].path, Op: FilterOp(scimFilterDollar[2].str), Value: scimFilterDollar[3].value}
		}
	case 18:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:152
		{
			scimFilterVAL.str = string(OpEqual)
		}
	case 19:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:156
		{
			scimFilterVAL.str = string(OpNotEqual)
		}
	case 20:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:160
		{
			scimFilterVAL.str = string(OpContains)
		}
	case 21:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:164
		{
			scimFilterVAL.str = string(OpStartsWith)
		}
	case 22:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:168
		{
			scimFilterVAL.str = string(OpEndsWith)
		}
	case 23:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:172
		{
			scimFilterVAL.str = string(OpGreaterThan)
		}
	case 24:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:176
		{
			scimFilterVAL.str = string(OpGreaterEqual)
		}
	case 25:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:180
		{
			scimFilterVAL.str = string(OpLessThan)
		}
	case 26:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:184
		{
			scimFilterVAL.str = string(OpLessEqual)
		}
	case 27:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:192
		{
			scimFilterVAL.value = false
		}
	case 28:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:196
		{
			scimFilterVAL.value = true
		}
	case 29:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:200
		{
			scimFilterVAL.value = nil
		}
	case 30:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:204
		{
			v, err := decodeFilterNumber(scimFilterDollar[1].str)
			if err != nil {
				scimFilterlex.(*filterLex).setError(err)
			}
			scimFilterVAL.value = v
		}
	case 31:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:212
		{
			v, err := decodeFilterString(scimFilterDollar[1].str)
			if err != nil {
				scimFilterlex.(*filterLex).setError(err)
			}
			scimFilterVAL.value = v
		}
	case 32:
		scimFilterDollar = scimFilterS[scimFilterpt-1 : scimFilterpt+1]
//line filter_grammar.y:224
		{
			scimFilterVAL.path = splitAttrPath(scimFilterDollar[1].str)
		}
	}
	goto scimFilterstack /* stack new state and value */
}
